


[server]
# If false, will attempt to open a browser window on start.
# Default: false unless (1) we are on a Linux box where DISPLAY is unset, or (2) server.liveSave is set.
headless = true

# The port where the server will listen for browser connections.
# Default: 8501
port = $PORT

# Enables support for Cross-Origin Request Sharing, for added security.
# Default: true
enableCORS = false
